app:
  name: currency
  port: 8080
mongodb:
  urls:
    - ds139853-a0.mlab.com:39853
    - ds139853-a1.mlab.com:39853
  port: 39853
  database: currency
  replica_set: rs-ds139853
  username: admin
  password: ETsHC6tQScRp
webservices:
  fixer:
    url: http://data.fixer.io/api
    api_key: cda0d18a191f78eb3ec4302b2bedbe39